# Generated by Django 3.2.6 on 2021-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210826_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('people', models.CharField(choices=[('1', '1 person'), ('2', '2 persons'), ('3', '3 persons'), ('4', '4 persons'), ('5', '5 persons'), ('6', 'More than 5 persons')], max_length=15)),
                ('package_name', models.CharField(max_length=100)),
            ],
        ),
    ]
